server:
    port: 8080

spring:
    datasource:
        username: root
        password: 1234w5asd
        url: jdbc:mysql://localhost:3306/finance?characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 30000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: false
            filter:
                stat:
                    log-slow-sql: true
                    db-type: mysql
                    slow-sql-millis: 2000
                    enabled: true
            web-stat-filter:
                enabled: true
                url-pattern: /*
                session-stat-enable: false
            stat-view-servlet:
                login-username: admin
                login-password: 123456
                allow: 127.0.0.1
                url-pattern: /druid/*
                enabled: true
            use-local-session-state: false
        type: com.alibaba.druid.pool.DruidDataSource
    redis:
        host: localhost
        database: 0
        port: 6379
        password:
        jedis:
            pool:
                max-active: 8
                max-wait: -1ms
                max-idle: 8
                min-idle: 0
        timeout: 3000ms


    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        mode: HTML
        servlet:
            content-type: text/html
mybatis:
    mapper-locations: classpath:/mapper/**/*.xml
